export const CUSTOMERS_LIST_MOCK_DATA = [
  {
    customerId: "Saal One",
    fullName: "Sathish",
    emailId: "Sathish@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "SathishE",
    picture: "saal_logo.svg",
    address: "UAE",
  },
  {
    customerId: "Dubai Saal",
    fullName: "Sathish",
    emailId: "Sathish@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "SathishE12",
    picture: "saal_logo.svg",
    address: "UAE",
  },
  {
    customerId: "One Saal",
    fullName: "Sathish",
    emailId: "Sathish@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "SathishE12",
    picture: "saal_logo.svg",
    address: "UAE",
  },
  {
    customerId: "One Saal",
    fullName: "Sathish",
    emailId: "Sathish@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "SathishE12",
    picture: "saal_logo.svg",
    address: "UAE",
  },
  {
    customerId: "One Saal",
    fullName: "Sathish",
    emailId: "Sathish@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "SathishE12",
    picture: "saal_logo.svg",
    address: "UAE",
  },
  {
    customerId: "One Saal",
    fullName: "Sathish",
    emailId: "Sathish@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "SathishE12",
    picture: "saal_logo.svg",
    address: "UAE",
  },
  {
    customerId: "One Saal",
    fullName: "Sathish",
    emailId: "Sathish@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "SathishE12",
    picture: "saal_logo.svg",
    address: "UAE",
  },
  {
    customerId: "One Saal",
    fullName: "Sathish",
    emailId: "Sathish@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "SathishE12",
    picture: "saal_logo.svg",
    address: "UAE",
  },
  {
    customerId: "One Saal",
    fullName: "Sathish",
    emailId: "Sathish@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "SathishE12",
    picture: "saal_logo.svg",
    address: "UAE",
  },
  {
    customerId: "One Saal",
    fullName: "Sathish",
    emailId: "Sathish@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "SathishE12",
    picture: "saal_logo.svg",
    address: "UAE",
  },
  {
    customerId: "Abu Dhabi Saal",
    fullName: "Sathish",
    emailId: "Sathish@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "SathishE12",
    picture: "saal_logo.svg",
    address: "UAE",
  },
];
