export const CUSTOMERS_LIST_MOCK_DATA = [
  {
    customerId: "Sust123",
    fullName: "Sathish Eskilla",
    emailId: "Sathish_Eskilla@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "Sathish123",
    picture: "saal_logo.svg",
    address: "India",
  },
  {
    customerId: "Abhi123",
    fullName: "Sathish Eskilla",
    emailId: "Sathish_Eskilla@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "Sathish123",
    picture: "saal_logo.svg",
    address: "India",
  },
  {
    customerId: "Suresh123",
    fullName: "Sathish Eskilla",
    emailId: "Sathish_Eskilla@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "Sathish123",
    picture: "saal_logo.svg",
    address: "India",
  },
  {
    customerId: "Cust123",
    fullName: "Sathish Eskilla",
    emailId: "Sathish_Eskilla@hotmail.com",
    mobileNumber: "98765423434",
    gender: "Male",
    userName: "Sathish123",
    picture: "saal_logo.svg",
    address: "USA",
  },
];
